name: Frontend Deploy to S3

on:
  push:
    branches: [ develop, master ]
    paths:
      - '**'  # 루트 디렉토리에서의 파일 변경 감지

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Node.js 설정
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.15.0'

      # 의존성 설치
      - name: Install dependencies
        run: npm install

      # 프로젝트 빌드
      - name: Build project
        run: npm run build

      # AWS 인증 설정
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # S3에 배포
      - name: Deploy to S3
        run: |
          aws s3 sync dist/ s3://${{ secrets.AWS_S3_BUCKET_NAME }} --delete

      # CloudFront 캐시 무효화
      - name: Invalidate CloudFront Cache
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_CLOUDFRONT_ID }} --paths "/*"